version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:11.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p102030}
      PGDATA: /data/postgres
    volumes:
       - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - environment-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.13
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin-data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - environment-network
    restart: unless-stopped
  
  activemq_artemis:
    container_name: activemq_artemis
    image: vromero/activemq-artemis:2.9.0
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - 61616:61616
      - 8161:8161
    networks:
      - environment-network
    restart: unless-stopped

  keycloak:
      container_name: keycloak
      image: jboss/keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: p102030
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      command: ["-Djboss.socket.binding.port-offset=100"]
      ports:
        - 8180:8180
      depends_on:
        - postgres
      networks:
        - environment-network

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - environment-network
    depends_on:
        - postgres
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
 

networks:
  environment-network:
    driver: bridge

volumes:
    postgres-data:
    pgadmin-data:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions: